name: Publish

on:
  push:
    branches: [ test-cd ]
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Modify package name
        run: sed -i 's/^name = "pacmap"/name = "pacmap-dev"/' pyproject.toml

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Build wheels
        run: uv build --wheel

      - uses: actions/upload-artifact@v4
        with:
          name: uv-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./dist/*.whl

      - name: Show artifacts
        run: ls -lh ./dist

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
        if: startsWith(github.ref, 'refs/tags/v') && github.event_name == 'push'